// <auto-generated />
using System;
using Eshop.Module.Basket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eshop.Module.Basket.Data.Migrations
{
    [DbContext(typeof(BasketDbContext))]
    partial class BasketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("basket")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LatestUpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CartItems", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("DiscountStep")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCouponRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("RuleToApply")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("StartOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsageLimitPerCoupon")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimitPerCustomer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CartRules", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CartRuleCategory", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleCustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartRuleId");

                    b.ToTable("CartRuleCustomerGroup", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartRuleProduct", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CartRuleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CartRuleId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartRuleId1");

                    b.HasIndex("CouponId");

                    b.ToTable("CartRuleUsages", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CatalogRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("EndOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("RuleToApply")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("StartOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CatalogRule", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CatalogRuleCustomerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerGroupId");

                    b.ToTable("CatalogRuleCustomerGroup", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartRuleId");

                    b.ToTable("Coupons", "basket");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleCategory", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CartRule", "CartRule")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartRule");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleCustomerGroup", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CartRule", "CartRule")
                        .WithMany("CustomerGroups")
                        .HasForeignKey("CartRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartRule");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleProduct", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CartRule", "CartRule")
                        .WithMany("Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartRule");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRuleUsage", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CartRule", "CartRule")
                        .WithMany()
                        .HasForeignKey("CartRuleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eshop.Module.Basket.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId");

                    b.Navigation("CartRule");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CatalogRuleCustomerGroup", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CatalogRule", "CatalogRule")
                        .WithMany("CustomerGroups")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogRule");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.Coupon", b =>
                {
                    b.HasOne("Eshop.Module.Basket.Models.CartRule", "CartRule")
                        .WithMany("Coupons")
                        .HasForeignKey("CartRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartRule");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CartRule", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Coupons");

                    b.Navigation("CustomerGroups");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Eshop.Module.Basket.Models.CatalogRule", b =>
                {
                    b.Navigation("CustomerGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
